### PR TITLE
updated version of revised plan

### PR DESCRIPTION
**Pull request by iamabhutta**

### CODE REVIEW

**Comment by mwand** [comment]
The opening para says:
> If there were any deficiencies or concerns noted by your TA mentor on your preliminary plan, you must address those concerns in this revised plan.

Is this reflected anywhere in the grading scheme?

**Comment by iamabhutta** [comment]
> The opening para says:
> 
> > If there were any deficiencies or concerns noted by your TA mentor on your preliminary plan, you must address those concerns in this revised plan.
> 
> Is this reflected anywhere in the grading scheme?

I don't see that anywhere (not on gradescope rubric too). Where should we add this?

**Comment by iamabhutta** [comment]
I have added this in Grading sections: "Any deficiencies or concerns noted by your TA mentor on your preliminary plan are addressed"

**Review by mwand — APPROVED** [review]
lgtm.

**Pull request merged**
