### PR TITLE
revised module 13 slides

### PR DESCRIPTION
**Pull request by mwand**
added new graphics, more detail about VMs vs. containers.  Clarified sharing at different levels of the software stack.

### CODE REVIEW

**Comment by iamabhutta** [comment]
lgtm. Nice additions

**Comment by mwand** [comment]
But doesn’t talk about docker. Will add tonight.

**Comment by iamabhutta** [comment]
Sure. Please merge when done. I am teaching m13 tomorrow

**Comment by mwand** [comment]
merged and pushed (from command line).

**Pull request merged**
