### PR TITLE
Modules 09 & 10

### PR DESCRIPTION
**Pull request by mwand**
This is really all one unit, which I've arbitrarily broken up into two modules.   Instructors who teach this material over two class sessions should split it at whatever point works.   

Module 10.3 (REST) is largely independent of the rest of the material and could be put at any place in the 09-10 sequence.

This PR is for the slides only; the activity, the module page, etc., will follow in a separate PR.

### CODE REVIEW

**Comment by mwand** [comment]
Should be ready to merge to main.

**Comment by iamabhutta** [comment]
Slides have old names (for instructors)
Links to module 10 file is broken.
You will need to merge main again since we have published the project plan (and will probably merge IP2 by the time this is ready for a merge)

**Comment by iamabhutta** [comment]
Taken care of things listed in my last comment.

**Comment by iamabhutta** [comment]
Slide 20 of 10.3 - text overlaps the code in pdf (was this supposed to be an animation?)
I still think, we need a slide that connects Module 10.1 to Module 3 - Structural scale in Design Principles 
Rest lgtm

**Comment by iamabhutta** [comment]
Are we still working on tutorial for REST/ Sockets?

**Comment by mwand** [comment]
I fixed the end of M10.3 .  Should be better now.   I am no longer working on REST/Socket tutorial.  The REST tutorial turned into 10.3.   The students seem to have learned about sockets from the materials that were posted along with IP1.

**Comment by mwand** [comment]
Didn't add the slide in 10.1 connecting w/ Module 3.   Too tired to do it
now, maybe tomorrow.

**Comment by mwand** [comment]
Added sentence in 10.1 speakers notes relating to M03.   Merging now.

**Pull request merged**
