### PR TITLE
Modules 13 and 14

### PR DESCRIPTION
**Pull request by janvitek**

### CODE REVIEW

**Comment by iamabhutta** [comment]
M13 comments from fa22: short lecture (finished in 35-40 minutes). Add more material? May be ask students to compare different cloud vendors and pricing and decide what would be appropriate if they were to host their project or app like coveytown

**Comment by iamabhutta** [comment]
Slides are same as last semester.
lgtm

**Comment by mwand** [comment]
whatever.  We should rethink this material next time.   lg(enough)tm.

**Comment by iamabhutta** [comment]
I am planning to let students work on IP2 if the lecture finishes early (module13), For module 14, if we finish early, I will check in with each group one by one to discuss the scope of the project and the feedback on preliminary project plan.

I will merge this later today or on the weekend.

**Pull request merged**
