### PR TITLE
initial draft of Module 05 Async

### PR DESCRIPTION
**Pull request by mwand**
Includes slides, examples, activity.   

Diffs from Fall: added more clarity about async, concurrency, and critical sections.  Students now have no excuse to fail on the midterm question we asked last Fall.

### CODE REVIEW

**Comment by iamabhutta** [comment]
Did you add a l5.md file? I don't see the slides linked to Module page.
Missing _data/modules.yml updates.
 If everything AFTER odds and ends slide is optional then perhaps we should move the Learning modules and activity slide earlier?
 Will take another pass at it later this week to review the slides closely.

**Comment by mwand** [comment]
No, I didn't.  That PR was intended as a draft.  I will add all the other
stuff soon.

**Comment by mwand** [comment]
I think this is ready to merge. @abhutta0 ?

**Comment by iamabhutta** [comment]
No. I thought you were going to review the slides on Friday. I will review them on Friday too and then we can merge on the weekend.

**Comment by mwand** [comment]
I've reviewed the slides; I think it's ready to merge.  If you'd like to review the slides, please feel free.  I will be at POPL all day on Friday, so I won't be able to do anything til Saturday.

**Comment by iamabhutta** [comment]
I will review tomorrow and will update/merge.

**Comment by abhutta0** [comment]
Left a comment on discord with details about the tweaks I made. If it looks good, then this is ready to merge.

**Pull request merged**
