### PR TITLE
Module 03

### PR DESCRIPTION
**Pull request by mwand**
(also did a tiny update to the module 02 activity, to use the correct lint setup).

### CODE REVIEW

**Comment by mwand** [comment]
Umm, does anyone know why the deploy failed?  When I try to look at the deploy log, I just get a blank console with a throbber.

**Comment by iamabhutta** [comment]
don't see anything in the log. May be try making another update and see if re-running it would work. Also updates to Module2 activity should go to main branch and then you can merge that with module03-branch. Also don't forget to update _data/modules.yml

**Comment by iamabhutta** [comment]
great. don't forget to update the link in _data/modules.yml otherwise calendars don't get updated. Thanks

**Comment by iamabhutta** [comment]
Module page doesn't include links to lecture slides. Perhaps you removed something from l3.md file.

**Comment by mwand** [comment]
ok, will do.

**Comment by iamabhutta** [comment]
lgtm

**Pull request merged**
