### PR TITLE
Calendars

### PR DESCRIPTION
**Pull request by iamabhutta**
Please review Calendars for your sections before we merge them

### CODE REVIEW

**Comment by mwand** [comment]
Branch deploy and Calendar now works, thanks.

But there are some problems.  Here are the first few things I noticed.

For week 10,  I can't plan on doing the midterm + anything else in the same
session-- even if I wanted to, DRC accommodations will introduce havoc.  So
there will have to be some shuffling.

April 12 appears twice:   once as week 13 and once as week 14.  Should week
13 be Wed, Apr 5?

Is the project due on Wed Apr 12 or Wed Apr 05? On the google spreadsheet,
it's 4/12 (week 13).  For section 3, at least, the Wed Apr12 due date
appears between Apr 03 and Apr 05

For week 13, the project is due at 11am on Wed Apr 12, so it doesn't make
sense to have "work on project" as a topic

On the web page, Spring Break is shown as week 9; on the spreadsheet, it is
a skipped week.  That's also how our spreadsheet for Spring 22 showed it.
 So I think that conflict has to be resolved before we can make any further
adjustments.

**Comment by iamabhutta** [comment]
For week 10,  we could leave it for exam only and move Security to week11. That way you could skip "Technical Debt" is you want.

Project is due on Wed Apr 12. It should now be fixed in all calendars.

For week 13, we can leave it for "work on project" and move ethics to week14 same day as the project deadline. I will temporarily leave "presentations on Week14 too in case we can't fit 15 presentations in Week15.

Spring Break is now week 9 in the spreadsheet.

**Comment by mwand** [comment]
lgtm.

**Comment by iamabhutta** [comment]
add kick off meeting to calendars.

**Comment by mwand** [comment]
Couldn't find the code diffs for this branch, so I don't know what was meant by "added kickoff meetings", but lgtm.

**Comment by iamabhutta** [comment]
That's a reminder for me to add that to calendar.

**Comment by mwand** [comment]
Oh.  What do you mean by "kickoff meetings"?

**Comment by iamabhutta** [comment]
That's when we publish the groups/teams and ask students to schedule their first meeting with TAs. That first meeting is "Kick-off" meeting.

**Pull request merged**
